//
// Copyright (C) 2010-2016 Micromata GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package de.micromata.genome.db.jdbc.wrapper;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Map;

/**
 * Not correct Use Wrapper directly.
 *
 * @author roger
 */
public class CallableStatementWrapper implements CallableStatement
{

  /**
   * The nested statement.
   */
  protected CallableStatement nestedStatement;

  /**
   * Instantiates a new callable statement wrapper.
   */
  public CallableStatementWrapper()
  {

  }

  /**
   * Instantiates a new callable statement wrapper.
   *
   * @param nestedStatement the nested statement
   */
  public CallableStatementWrapper(CallableStatement nestedStatement)
  {
    this.nestedStatement = nestedStatement;
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void addBatch() throws SQLException
  {
    nestedStatement.addBatch();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void addBatch(String sql) throws SQLException
  {
    nestedStatement.addBatch(sql);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void cancel() throws SQLException
  {
    nestedStatement.cancel();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void clearBatch() throws SQLException
  {
    nestedStatement.clearBatch();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void clearParameters() throws SQLException
  {
    nestedStatement.clearParameters();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void clearWarnings() throws SQLException
  {
    nestedStatement.clearWarnings();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void close() throws SQLException
  {
    nestedStatement.close();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public boolean execute() throws SQLException
  {
    return nestedStatement.execute();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public boolean execute(String sql, int autoGeneratedKeys) throws SQLException
  {
    return nestedStatement.execute(sql, autoGeneratedKeys);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public boolean execute(String sql, int[] columnIndexes) throws SQLException
  {
    return nestedStatement.execute(sql, columnIndexes);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public boolean execute(String sql, String[] columnNames) throws SQLException
  {
    return nestedStatement.execute(sql, columnNames);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public boolean execute(String sql) throws SQLException
  {
    return nestedStatement.execute(sql);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int[] executeBatch() throws SQLException
  {
    return nestedStatement.executeBatch();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public ResultSet executeQuery() throws SQLException
  {
    return nestedStatement.executeQuery();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public ResultSet executeQuery(String sql) throws SQLException
  {
    return nestedStatement.executeQuery(sql);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int executeUpdate() throws SQLException
  {
    return nestedStatement.executeUpdate();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException
  {
    return nestedStatement.executeUpdate(sql, autoGeneratedKeys);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int executeUpdate(String sql, int[] columnIndexes) throws SQLException
  {
    return nestedStatement.executeUpdate(sql, columnIndexes);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int executeUpdate(String sql, String[] columnNames) throws SQLException
  {
    return nestedStatement.executeUpdate(sql, columnNames);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int executeUpdate(String sql) throws SQLException
  {
    return nestedStatement.executeUpdate(sql);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Array getArray(int i) throws SQLException
  {
    return nestedStatement.getArray(i);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Array getArray(String parameterName) throws SQLException
  {
    return nestedStatement.getArray(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public BigDecimal getBigDecimal(int parameterIndex, int scale) throws SQLException
  {
    return nestedStatement.getBigDecimal(parameterIndex).setScale(scale);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public BigDecimal getBigDecimal(int parameterIndex) throws SQLException
  {
    return nestedStatement.getBigDecimal(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public BigDecimal getBigDecimal(String parameterName) throws SQLException
  {
    return nestedStatement.getBigDecimal(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Blob getBlob(int i) throws SQLException
  {
    return nestedStatement.getBlob(i);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Blob getBlob(String parameterName) throws SQLException
  {
    return nestedStatement.getBlob(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public boolean getBoolean(int parameterIndex) throws SQLException
  {
    return nestedStatement.getBoolean(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public boolean getBoolean(String parameterName) throws SQLException
  {
    return nestedStatement.getBoolean(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public byte getByte(int parameterIndex) throws SQLException
  {
    return nestedStatement.getByte(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public byte getByte(String parameterName) throws SQLException
  {
    return nestedStatement.getByte(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public byte[] getBytes(int parameterIndex) throws SQLException
  {
    return nestedStatement.getBytes(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public byte[] getBytes(String parameterName) throws SQLException
  {
    return nestedStatement.getBytes(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Clob getClob(int i) throws SQLException
  {
    return nestedStatement.getClob(i);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Clob getClob(String parameterName) throws SQLException
  {
    return nestedStatement.getClob(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Connection getConnection() throws SQLException
  {
    return nestedStatement.getConnection();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Date getDate(int parameterIndex, Calendar cal) throws SQLException
  {
    return nestedStatement.getDate(parameterIndex, cal);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Date getDate(int parameterIndex) throws SQLException
  {
    return nestedStatement.getDate(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Date getDate(String parameterName, Calendar cal) throws SQLException
  {
    return nestedStatement.getDate(parameterName, cal);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Date getDate(String parameterName) throws SQLException
  {
    return nestedStatement.getDate(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public double getDouble(int parameterIndex) throws SQLException
  {
    return nestedStatement.getDouble(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public double getDouble(String parameterName) throws SQLException
  {
    return nestedStatement.getDouble(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int getFetchDirection() throws SQLException
  {
    return nestedStatement.getFetchDirection();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int getFetchSize() throws SQLException
  {
    return nestedStatement.getFetchSize();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public float getFloat(int parameterIndex) throws SQLException
  {
    return nestedStatement.getFloat(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public float getFloat(String parameterName) throws SQLException
  {
    return nestedStatement.getFloat(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public ResultSet getGeneratedKeys() throws SQLException
  {
    return nestedStatement.getGeneratedKeys();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int getInt(int parameterIndex) throws SQLException
  {
    return nestedStatement.getInt(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int getInt(String parameterName) throws SQLException
  {
    return nestedStatement.getInt(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public long getLong(int parameterIndex) throws SQLException
  {
    return nestedStatement.getLong(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public long getLong(String parameterName) throws SQLException
  {
    return nestedStatement.getLong(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int getMaxFieldSize() throws SQLException
  {
    return nestedStatement.getMaxFieldSize();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int getMaxRows() throws SQLException
  {
    return nestedStatement.getMaxRows();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public ResultSetMetaData getMetaData() throws SQLException
  {
    return nestedStatement.getMetaData();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public boolean getMoreResults() throws SQLException
  {
    return nestedStatement.getMoreResults();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public boolean getMoreResults(int current) throws SQLException
  {
    return nestedStatement.getMoreResults(current);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Object getObject(int i, Map<String, Class<?>> map) throws SQLException
  {
    return nestedStatement.getObject(i, map);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Object getObject(int parameterIndex) throws SQLException
  {
    return nestedStatement.getObject(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Object getObject(String parameterName, Map<String, Class<?>> map) throws SQLException
  {
    return nestedStatement.getObject(parameterName, map);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Object getObject(String parameterName) throws SQLException
  {
    return nestedStatement.getObject(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public ParameterMetaData getParameterMetaData() throws SQLException
  {
    return nestedStatement.getParameterMetaData();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int getQueryTimeout() throws SQLException
  {
    return nestedStatement.getQueryTimeout();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Ref getRef(int i) throws SQLException
  {
    return nestedStatement.getRef(i);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Ref getRef(String parameterName) throws SQLException
  {
    return nestedStatement.getRef(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public ResultSet getResultSet() throws SQLException
  {
    return nestedStatement.getResultSet();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int getResultSetConcurrency() throws SQLException
  {
    return nestedStatement.getResultSetConcurrency();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int getResultSetHoldability() throws SQLException
  {
    return nestedStatement.getResultSetHoldability();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int getResultSetType() throws SQLException
  {
    return nestedStatement.getResultSetType();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public short getShort(int parameterIndex) throws SQLException
  {
    return nestedStatement.getShort(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public short getShort(String parameterName) throws SQLException
  {
    return nestedStatement.getShort(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public String getString(int parameterIndex) throws SQLException
  {
    return nestedStatement.getString(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public String getString(String parameterName) throws SQLException
  {
    return nestedStatement.getString(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Time getTime(int parameterIndex, Calendar cal) throws SQLException
  {
    return nestedStatement.getTime(parameterIndex, cal);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Time getTime(int parameterIndex) throws SQLException
  {
    return nestedStatement.getTime(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Time getTime(String parameterName, Calendar cal) throws SQLException
  {
    return nestedStatement.getTime(parameterName, cal);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Time getTime(String parameterName) throws SQLException
  {
    return nestedStatement.getTime(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Timestamp getTimestamp(int parameterIndex, Calendar cal) throws SQLException
  {
    return nestedStatement.getTimestamp(parameterIndex, cal);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Timestamp getTimestamp(int parameterIndex) throws SQLException
  {
    return nestedStatement.getTimestamp(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Timestamp getTimestamp(String parameterName, Calendar cal) throws SQLException
  {
    return nestedStatement.getTimestamp(parameterName, cal);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Timestamp getTimestamp(String parameterName) throws SQLException
  {
    return nestedStatement.getTimestamp(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public int getUpdateCount() throws SQLException
  {
    return nestedStatement.getUpdateCount();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public URL getURL(int parameterIndex) throws SQLException
  {
    return nestedStatement.getURL(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public URL getURL(String parameterName) throws SQLException
  {
    return nestedStatement.getURL(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public SQLWarning getWarnings() throws SQLException
  {
    return nestedStatement.getWarnings();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void registerOutParameter(int parameterIndex, int sqlType, int scale) throws SQLException
  {
    nestedStatement.registerOutParameter(parameterIndex, sqlType, scale);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void registerOutParameter(int paramIndex, int sqlType, String typeName) throws SQLException
  {
    nestedStatement.registerOutParameter(paramIndex, sqlType, typeName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void registerOutParameter(int parameterIndex, int sqlType) throws SQLException
  {
    nestedStatement.registerOutParameter(parameterIndex, sqlType);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void registerOutParameter(String parameterName, int sqlType, int scale) throws SQLException
  {
    nestedStatement.registerOutParameter(parameterName, sqlType, scale);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void registerOutParameter(String parameterName, int sqlType, String typeName) throws SQLException
  {
    nestedStatement.registerOutParameter(parameterName, sqlType, typeName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void registerOutParameter(String parameterName, int sqlType) throws SQLException
  {
    nestedStatement.registerOutParameter(parameterName, sqlType);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setArray(int i, Array x) throws SQLException
  {
    nestedStatement.setArray(i, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException
  {
    nestedStatement.setAsciiStream(parameterIndex, x, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setAsciiStream(String parameterName, InputStream x, int length) throws SQLException
  {
    nestedStatement.setAsciiStream(parameterName, x, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException
  {
    nestedStatement.setBigDecimal(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBigDecimal(String parameterName, BigDecimal x) throws SQLException
  {
    nestedStatement.setBigDecimal(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException
  {
    nestedStatement.setBinaryStream(parameterIndex, x, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBinaryStream(String parameterName, InputStream x, int length) throws SQLException
  {
    nestedStatement.setBinaryStream(parameterName, x, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBlob(int i, Blob x) throws SQLException
  {
    nestedStatement.setBlob(i, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBoolean(int parameterIndex, boolean x) throws SQLException
  {
    nestedStatement.setBoolean(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBoolean(String parameterName, boolean x) throws SQLException
  {
    nestedStatement.setBoolean(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setByte(int parameterIndex, byte x) throws SQLException
  {
    nestedStatement.setByte(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setByte(String parameterName, byte x) throws SQLException
  {
    nestedStatement.setByte(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBytes(int parameterIndex, byte[] x) throws SQLException
  {
    nestedStatement.setBytes(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBytes(String parameterName, byte[] x) throws SQLException
  {
    nestedStatement.setBytes(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setCharacterStream(int parameterIndex, Reader reader, int length) throws SQLException
  {
    nestedStatement.setCharacterStream(parameterIndex, reader, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setCharacterStream(String parameterName, Reader reader, int length) throws SQLException
  {
    nestedStatement.setCharacterStream(parameterName, reader, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setClob(int i, Clob x) throws SQLException
  {
    nestedStatement.setClob(i, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setCursorName(String name) throws SQLException
  {
    nestedStatement.setCursorName(name);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException
  {
    nestedStatement.setDate(parameterIndex, x, cal);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setDate(int parameterIndex, Date x) throws SQLException
  {
    nestedStatement.setDate(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setDate(String parameterName, Date x, Calendar cal) throws SQLException
  {
    nestedStatement.setDate(parameterName, x, cal);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setDate(String parameterName, Date x) throws SQLException
  {
    nestedStatement.setDate(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setDouble(int parameterIndex, double x) throws SQLException
  {
    nestedStatement.setDouble(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setDouble(String parameterName, double x) throws SQLException
  {
    nestedStatement.setDouble(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setEscapeProcessing(boolean enable) throws SQLException
  {
    nestedStatement.setEscapeProcessing(enable);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setFetchDirection(int direction) throws SQLException
  {
    nestedStatement.setFetchDirection(direction);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setFetchSize(int rows) throws SQLException
  {
    nestedStatement.setFetchSize(rows);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setFloat(int parameterIndex, float x) throws SQLException
  {
    nestedStatement.setFloat(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setFloat(String parameterName, float x) throws SQLException
  {
    nestedStatement.setFloat(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setInt(int parameterIndex, int x) throws SQLException
  {
    nestedStatement.setInt(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setInt(String parameterName, int x) throws SQLException
  {
    nestedStatement.setInt(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setLong(int parameterIndex, long x) throws SQLException
  {
    nestedStatement.setLong(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setLong(String parameterName, long x) throws SQLException
  {
    nestedStatement.setLong(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setMaxFieldSize(int max) throws SQLException
  {
    nestedStatement.setMaxFieldSize(max);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setMaxRows(int max) throws SQLException
  {
    nestedStatement.setMaxRows(max);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNull(int paramIndex, int sqlType, String typeName) throws SQLException
  {
    nestedStatement.setNull(paramIndex, sqlType, typeName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNull(int parameterIndex, int sqlType) throws SQLException
  {
    nestedStatement.setNull(parameterIndex, sqlType);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNull(String parameterName, int sqlType, String typeName) throws SQLException
  {
    nestedStatement.setNull(parameterName, sqlType, typeName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNull(String parameterName, int sqlType) throws SQLException
  {
    nestedStatement.setNull(parameterName, sqlType);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setObject(int parameterIndex, Object x, int targetSqlType, int scale) throws SQLException
  {
    nestedStatement.setObject(parameterIndex, x, targetSqlType, scale);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException
  {
    nestedStatement.setObject(parameterIndex, x, targetSqlType);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setObject(int parameterIndex, Object x) throws SQLException
  {
    nestedStatement.setObject(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setObject(String parameterName, Object x, int targetSqlType, int scale) throws SQLException
  {
    nestedStatement.setObject(parameterName, x, targetSqlType, scale);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setObject(String parameterName, Object x, int targetSqlType) throws SQLException
  {
    nestedStatement.setObject(parameterName, x, targetSqlType);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setObject(String parameterName, Object x) throws SQLException
  {
    nestedStatement.setObject(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setQueryTimeout(int seconds) throws SQLException
  {
    nestedStatement.setQueryTimeout(seconds);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setRef(int i, Ref x) throws SQLException
  {
    nestedStatement.setRef(i, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setShort(int parameterIndex, short x) throws SQLException
  {
    nestedStatement.setShort(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setShort(String parameterName, short x) throws SQLException
  {
    nestedStatement.setShort(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setString(int parameterIndex, String x) throws SQLException
  {
    nestedStatement.setString(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setString(String parameterName, String x) throws SQLException
  {
    nestedStatement.setString(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException
  {
    nestedStatement.setTime(parameterIndex, x, cal);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setTime(int parameterIndex, Time x) throws SQLException
  {
    nestedStatement.setTime(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setTime(String parameterName, Time x, Calendar cal) throws SQLException
  {
    nestedStatement.setTime(parameterName, x, cal);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setTime(String parameterName, Time x) throws SQLException
  {
    nestedStatement.setTime(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException
  {
    nestedStatement.setTimestamp(parameterIndex, x, cal);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException
  {
    nestedStatement.setTimestamp(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setTimestamp(String parameterName, Timestamp x, Calendar cal) throws SQLException
  {
    nestedStatement.setTimestamp(parameterName, x, cal);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setTimestamp(String parameterName, Timestamp x) throws SQLException
  {
    nestedStatement.setTimestamp(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException
  {
    nestedStatement.setUnicodeStream(parameterIndex, x, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Reader getCharacterStream(int parameterIndex) throws SQLException
  {
    return nestedStatement.getCharacterStream(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Reader getCharacterStream(String parameterName) throws SQLException
  {
    return nestedStatement.getCharacterStream(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Reader getNCharacterStream(int parameterIndex) throws SQLException
  {
    return nestedStatement.getNCharacterStream(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public Reader getNCharacterStream(String parameterName) throws SQLException
  {
    return nestedStatement.getNCharacterStream(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public NClob getNClob(int parameterIndex) throws SQLException
  {
    return nestedStatement.getNClob(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public NClob getNClob(String parameterName) throws SQLException
  {
    return nestedStatement.getNClob(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public String getNString(int parameterIndex) throws SQLException
  {
    return nestedStatement.getNString(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public String getNString(String parameterName) throws SQLException
  {
    return nestedStatement.getNString(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public RowId getRowId(int parameterIndex) throws SQLException
  {
    return nestedStatement.getRowId(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public RowId getRowId(String parameterName) throws SQLException
  {
    return nestedStatement.getRowId(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public SQLXML getSQLXML(int parameterIndex) throws SQLException
  {
    return nestedStatement.getSQLXML(parameterIndex);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public SQLXML getSQLXML(String parameterName) throws SQLException
  {
    return nestedStatement.getSQLXML(parameterName);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public boolean isClosed() throws SQLException
  {
    return nestedStatement.isClosed();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public boolean isPoolable() throws SQLException
  {
    return nestedStatement.isPoolable();
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public boolean isWrapperFor(Class<?> iface) throws SQLException
  {
    return nestedStatement.isWrapperFor(iface);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException
  {
    nestedStatement.setAsciiStream(parameterIndex, x, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException
  {
    nestedStatement.setAsciiStream(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setAsciiStream(String parameterName, InputStream x, long length) throws SQLException
  {
    nestedStatement.setAsciiStream(parameterName, x, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setAsciiStream(String parameterName, InputStream x) throws SQLException
  {
    nestedStatement.setAsciiStream(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException
  {
    nestedStatement.setBinaryStream(parameterIndex, x, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException
  {
    nestedStatement.setBinaryStream(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBinaryStream(String parameterName, InputStream x, long length) throws SQLException
  {
    nestedStatement.setBinaryStream(parameterName, x, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBinaryStream(String parameterName, InputStream x) throws SQLException
  {
    nestedStatement.setBinaryStream(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException
  {
    nestedStatement.setBlob(parameterIndex, inputStream, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException
  {
    nestedStatement.setBlob(parameterIndex, inputStream);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBlob(String parameterName, Blob x) throws SQLException
  {
    nestedStatement.setBlob(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBlob(String parameterName, InputStream inputStream, long length) throws SQLException
  {
    nestedStatement.setBlob(parameterName, inputStream, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setBlob(String parameterName, InputStream inputStream) throws SQLException
  {
    nestedStatement.setBlob(parameterName, inputStream);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException
  {
    nestedStatement.setCharacterStream(parameterIndex, reader, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException
  {
    nestedStatement.setCharacterStream(parameterIndex, reader);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setCharacterStream(String parameterName, Reader reader, long length) throws SQLException
  {
    nestedStatement.setCharacterStream(parameterName, reader, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setCharacterStream(String parameterName, Reader reader) throws SQLException
  {
    nestedStatement.setCharacterStream(parameterName, reader);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setClob(int parameterIndex, Reader reader, long length) throws SQLException
  {
    nestedStatement.setClob(parameterIndex, reader, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setClob(int parameterIndex, Reader reader) throws SQLException
  {
    nestedStatement.setClob(parameterIndex, reader);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setClob(String parameterName, Clob x) throws SQLException
  {
    nestedStatement.setClob(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setClob(String parameterName, Reader reader, long length) throws SQLException
  {
    nestedStatement.setClob(parameterName, reader, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setClob(String parameterName, Reader reader) throws SQLException
  {
    nestedStatement.setClob(parameterName, reader);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException
  {
    nestedStatement.setNCharacterStream(parameterIndex, value, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException
  {
    nestedStatement.setNCharacterStream(parameterIndex, value);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNCharacterStream(String parameterName, Reader value, long length) throws SQLException
  {
    nestedStatement.setNCharacterStream(parameterName, value, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNCharacterStream(String parameterName, Reader value) throws SQLException
  {
    nestedStatement.setNCharacterStream(parameterName, value);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNClob(int parameterIndex, NClob value) throws SQLException
  {
    nestedStatement.setNClob(parameterIndex, value);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException
  {
    nestedStatement.setNClob(parameterIndex, reader, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNClob(int parameterIndex, Reader reader) throws SQLException
  {
    nestedStatement.setNClob(parameterIndex, reader);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNClob(String parameterName, NClob value) throws SQLException
  {
    nestedStatement.setNClob(parameterName, value);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNClob(String parameterName, Reader reader, long length) throws SQLException
  {
    nestedStatement.setNClob(parameterName, reader, length);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNClob(String parameterName, Reader reader) throws SQLException
  {
    nestedStatement.setNClob(parameterName, reader);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNString(int parameterIndex, String value) throws SQLException
  {
    nestedStatement.setNString(parameterIndex, value);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setNString(String parameterName, String value) throws SQLException
  {
    nestedStatement.setNString(parameterName, value);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setPoolable(boolean poolable) throws SQLException
  {
    nestedStatement.setPoolable(poolable);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setRowId(int parameterIndex, RowId x) throws SQLException
  {
    nestedStatement.setRowId(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setRowId(String parameterName, RowId x) throws SQLException
  {
    nestedStatement.setRowId(parameterName, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException
  {
    nestedStatement.setSQLXML(parameterIndex, xmlObject);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setSQLXML(String parameterName, SQLXML xmlObject) throws SQLException
  {
    nestedStatement.setSQLXML(parameterName, xmlObject);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException
  {
    return nestedStatement.unwrap(iface);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setURL(int parameterIndex, URL x) throws SQLException
  {
    nestedStatement.setURL(parameterIndex, x);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void setURL(String parameterName, URL val) throws SQLException
  {
    nestedStatement.setURL(parameterName, val);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public boolean wasNull() throws SQLException
  {
    return nestedStatement.wasNull();
  }

  /**
   * Gets the nested statement.
   *
   * @return the nested statement
   */
  public CallableStatement getNestedStatement()
  {
    return nestedStatement;
  }

  /**
   * Sets the nested statement.
   *
   * @param nestedStatement the new nested statement
   */
  public void setNestedStatement(CallableStatement nestedStatement)
  {
    this.nestedStatement = nestedStatement;
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public void closeOnCompletion() throws SQLException
  {
    Jdbc17Utils.invoke(nestedStatement, SQLException.class, "closeOnCompletion");
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  public boolean isCloseOnCompletion() throws SQLException
  {
    return (Boolean) Jdbc17Utils.invoke(nestedStatement, SQLException.class, "isCloseOnCompletion");
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  @SuppressWarnings("unchecked")
  public <T> T getObject(int parameterIndex, Class<T> type) throws SQLException
  {
    return (T) Jdbc17Utils.invoke(nestedStatement, SQLException.class, "getObject", parameterIndex, type);
  }

  /**
   * {@inheritDoc}
   *
   */

  @Override
  @SuppressWarnings("unchecked")
  public <T> T getObject(String parameterName, Class<T> type) throws SQLException
  {
    return (T) Jdbc17Utils.invoke(nestedStatement, SQLException.class, "getObject", parameterName, type);
  }

}
